apps/article/urls.py
from django.urls import path

from article import views

app_name = '[article]'
urlpatterns = [

    path('created/', views.Article_Add, name='created'),

    path('', views.ArticleList, name='index'),
    path('me/', views.ArticleMe, name='me'),
    path('blog_img_upload/', views.blog_img_upload, name='blog_img_upload'),
    path('detail/<uuid:article_id>', views.Article_detail, name='detail'),
    path('update/<uuid:article_id>', views.ArticleUpdate, name='update'),
    path('update_image/<uuid:article_id>', views.RemoveImage, name='update_image'),
    path('delete/', views.ArticleDelete, name='delete'),
    path('api/', views.api, name='api'),
    path('apis/', views.addModel),

]

apps/forum/urls.py
from django.urls import path

app_name='[forum]'
from . import views
urlpatterns = [
  path('',views.index,name='forum'),
  path('add/',views.add_forum,name='add'),
  path('detail/<uuid:forum_id>/',views.forum_detail,name='detail'),
  path('cagetory/<int:category>/',views.forum_category,name='id'),
  path('del/<uuid:id>/',views.delForum,name='del'),
  ]

apps/support/urls.py
from django.urls import path

app_name='support'
from . import views
urlpatterns = [
    # path('',views.login_view,name='index'),
    path('', views.index, name='support'),
]

apps/user/urls.py
from django.urls import path
from apps.forum.views import indexMe
from user import views

app_name = '[user]'

urlpatterns = [
    # path('',views.login_view,name='index'),
    path('', views.Person.as_view(), name='person'),
    path('author/', views.Author.as_view(), name='author'),
    path('<uuid:article_id>/', views.PersonDetaile.as_view(), name='author_detaile'),
    path('info/<uuid:article_id>/', views.InfoOthers.as_view(), name='info'),
    path('ProfileOthers/<uuid:article_id>/', views.ProfileOthers, name='ProfileOthers'),
    path('profile/', views.Profile, name='profile'),
    path('info/', views.Info, name='info'),
    path('forum/', indexMe, name='forum'),
    path('modify/', views.Modify.as_view(), name='modify'),
    path('retrieve/', views.Retrieve.as_view(), name='retrieve '),
    path('sing_email/', views.ResetUserView.as_view(), name='sing_email'),
    path('email_update/', views.EmailView.as_view(), name='email_update'),
    path('Guan/', views.Guan, name='Guan'),
    path('retrieveEmail/', views.RetrieveEmail.as_view(), name='retrieveEmail'),
    path('message/', views.message, name='message'),
    path('bindingQQ/', views.bindingQQ, name='bindingQQ'),
]

website/urls.py
from django.conf import settings
from django.views.generic import TemplateView
from django.views.static import serve
from rest_framework import routers
from rest_framework.documentation import include_docs_urls
from rest_framework_jwt.views import obtain_jwt_token

from article import views
from article.api import FollowListView, ArticleCommit, MeArticleListView, ArticleListView, CategoryView, \
    ArticleCommintView, ArticleCommentReplyView, ArticleCreated
from course.views import CoursesList, MeCoursesList, CourseCreatedList, CourseListCreated
from forum.api import Forum_plateView, ForumView, CommentView, Parent_CommentView
from support.views import BannerList, EmailsList, LinkList, QQList, SeoList
from user.views import test, captcha_refresh, login_view, logout_view, to_login, Register, yan, getClbackQQ, \
    get_message, PersonApi, UserMessages, UserGetInfo, UserGetAllInfo, PersonOthers, getClback, active_user, qq
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path

router = routers.DefaultRouter()
router.register('article_list', ArticleListView)
router.register('me_article_list', MeArticleListView)
router.register('ArticleCommit', ArticleCommit)
router.register('follow_list', FollowListView)
router.register('category', CategoryView)
router.register('article_Comment', ArticleCommintView)
router.register('comment_reply', ArticleCommentReplyView)
router.register('PersonApi', PersonApi)
router.register('info', UserGetInfo)
router.register('all_info', UserGetAllInfo)
# router.register('user_disbale', UserDisbale)
router.register('PersonOthers', PersonOthers)
router.register('UserMessages', UserMessages, base_name='UserMessages')
router.register('article', ArticleCreated)
router.register('courseList', CoursesList)
router.register('mecourseList', MeCoursesList)
router.register('course', CourseCreatedList)
router.register('Addtutorial', CourseListCreated)
router.register('BannerList', BannerList)
router.register('EmailsList', EmailsList)
router.register('LinkList', LinkList)
router.register('forum/category', Forum_plateView)
router.register('forum', ForumView)
router.register('CommentView', CommentView)
router.register('Parent_CommentView', Parent_CommentView)
router.register('get-list',QQList)
router.register('seo-list',SeoList,basename='seo-list')
urlpatterns = [
    # path('admins/', admin.site.urls),
    path('admin/', TemplateView.as_view(template_name='admin/index.html')),
    # path('',test), # 这是生成验证码的图片
    url(r'^captcha/', include('captcha.urls')),
    path('refresh/', captcha_refresh),  # 这是生成验证码的图片
    path('yan/', yan),  # 这是生成验证码的图片
    path('', views.Article_list, name='home'),
    path('54', views.test, name='54'),
    path('login/', login_view, name='index'),
    path('info/', get_message, name='info'),
    path('person/', include('apps.user.urls',namespace='user')),
    path('logou/', logout_view, name='logou'),
    path('register/', Register.as_view(), name='register'),
    path('article/', include('apps.article.urls',namespace='article')),
    path('course/', include('apps.course.urls',namespace='course')),
    path('support/', include('apps.support.urls',namespace='support')),
    path('forum/', include('apps.forum.urls',namespace='forum')),
    url(r'^activate/(?P<token>\w+.[-_\w]*\w+.[-_\w]*\w+)/$', active_user, name='active_user'),
    path('activate/<str:token>', active_user, name='active_user'),
    url(r'^search/', include('haystack.urls'), name='haystack_search'),

    re_path(r'^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("api-docs/", include_docs_urls("API文档")),
    re_path(r'api/login/$', obtain_jwt_token),  # jwt认证
    url('auth-qq', to_login, name='qq-login'),
    url('qq', qq, name='qq'),
    url('callbackget', getClback, name='callbackget'),
    url('getClbackQQ', getClbackQQ, name='getClbackQQ'),
    # re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATI_ROOT})  # 配置文件上传html显示

]

apps/article/forms.py
from django import forms

from article.models import Article


class Article_form(forms.ModelForm):
    category = forms.IntegerField(required=True)

    class Meta:
        model = Article
        fields = ['title', 'authors', 'content']

apps/forum/forms.py
from django import forms

from forum.models import Forum,Parent_Comment


class Forum_form(forms.ModelForm):
    '''
    发布帖子
    '''
    category  = forms.IntegerField(required=True)
    class Meta:
        model= Forum
        fields = ['title','authors','content']

class ParentComment(forms.ModelForm):
    class Meta:
        model = Parent_Comment
        fields = ['comments','user','forums','parent_comments','to_Parent_Comments','url']

apps/article/views.py
import datetime
import json
import os
import random

import requests
import urllib3
from PIL import Image
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from rest_framework.pagination import PageNumberPagination

from article.forms import Article_form
from article.models import Article, Recommend, Category_Article, Headlines
from article.tasks import error_email
from forum.models import Forum
from support.models import *
from user.models import Follows
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from utils.jsonserializable import DateEncoder

User = get_user_model()


def test(request):
    WorkList = []
    for i in range(1, 100):
        WorkList.append(Forum(
            title='```cpp\n下例 中的某些语句读不太明白：\n 1.   DataTable dt=ds.Tables[\"cs\"] 这句最难理解，意思是读取cs表赋给新建的内存表dt（复制表）?还是dt表指向（引用）cs表，修改dt其实就是修改cs?\n 2.   sda.FillSchema(dt,SchemaType.Mapped); 这句应该是将数据库表中的元数据填入到dt中，为何要填入?cs表中没有元数据吗?\n 3.   此例中修改了dt表，执行Update为何更新了数据库?dt、cs与数据库是个怎么个联系?\n\n\n例：\nSqlConnection ds;\nDataSet ds;\nSqlDataAdapter sda;\n...........        \nDataTable dt=ds.Tables[\"cs\"];\nsda.FillSchema(dt,SchemaType.Mapped);\nDataRow dr=dt.Rows.Find(txtNo.text);\ndr[\"姓名\"]=txtName.Text.Trim();\ndr[\"性别\"]=txtSex.Text.Trim();\nSqlCommandBuilder cmdbuilder=new SqlCommandBuilder(sda);\nsda.Update(dt);\n```%s' % (
                i), category_id=4, authors_id='7d4d01419d1d491ab7c399b3c965b'))
    Forum.objects.bulk_create(WorkList)
    return HttpResponse('ok')


def Article_list(request):
    '''
    首页
    :param request:
    :return:
    '''
    from support.models import link
    article = Article.objects.filter(is_show=True)[:100]
    popular = Article.objects.filter(is_show=True).order_by('click_nums')[:5]
    recommend = Recommend.objects.filter(is_recommend=True)[:10]
    qq = QQ.objects.all()
    links = link.objects.all()

    user = Follows.objects.values('follow_id').distinct().order_by('-follow_id')
    item = []
    for i in user:
        data = {}
        data['data'] = User.objects.filter(follow__follow__id=i['follow_id']).distinct()
        item.append(data)

    try:
        page = request.GET.get('page', 1)
        if page == '':
            page = 1

    except PageNotAnInteger:
        page = request.GET.get('page')
    p = Paginator(article, 10, request=request)
    people = p.page(page)
    if request.is_ajax():
        json_dict = {}
        json_dict['data'] = []
        data = p.page(page).object_list
        print(people.has_next())
        json_dict['status'] = people.has_next()
        json_dict['num_pages'] = people.num_pages
        json_dict['page'] = page
        for i in data:
            list_dict = {}
            list_dict = {}
            list_dict['title'] = i.title
            list_dict['id'] = i.id
            list_dict['username'] = i.authors.username
            list_dict['userId'] = i.authors.id
            list_dict['userImag'] = i.authors.user_imag
            list_dict['userImage'] = i.authors.user_image
            list_dict['category'] = i.category.name
            list_dict['click_nums'] = i.click_nums
            list_dict['desc'] = i.desc
            list_dict['list_pic'] = i.list_pic
            list_dict['add_time'] = i.add_time
            article_comment = i.article_comment_set.all()
            article_comment_childer = i.article_comment_set.count()
            for i in article_comment:
                article_comment_childer += i.articlecommentreply_set.count()
            json_dict['data'].append(list_dict)
        return JsonResponse(json_dict, safe=False, encoder=DateEncoder)
    banners = Banners.objects.first()
    return render(request, 'pc/index.html',
                  {'article': people, 'qq': qq, 'popular': popular, 'count': item, 'recommend': recommend,
                   'links': links, 'banners': banners})


def ArticleList(request):
    '''
    文章列表
    :param request:
    :return:
    '''
    article = Article.objects.filter(is_show=True)
    category = Category_Article.objects.all()
    type = request.GET.get('type', '')
    try:
        page = request.GET.get('page', 1)
        if type:
            article = article.filter(category_id=type)
            if page == '':
                page = 1
    except PageNotAnInteger:
        page = 1

    p = Paginator(article, 10, request=request)
    people = p.page(page)
    headlines = Headlines.objects.all()[:30]
    banners = Banners.objects.first()

    return render(request, 'pc/article.html',
                  {'article': people, 'category': category, 'Headlines': headlines, 'banners': banners})


def api(request):
    # TODO: 修改
    url = 'http://v.juhe.cn/toutiao/index?type=keji&key={0}'.format(conf.get('AppKey', 'key'))
    headers = {
        "Accept-Encoding": "gzip",
        "Connection": "close"
    }
    r = requests.get(url, headers=headers)
    print(r.json())
    if r.status_code == requests.codes.ok:
        dict_json = r.json()
        print(dict_json['result']['data'])
        main = Headlines()
        list_dict = []
        for item in dict_json['result']['data']:
            obj = Headlines(
                url=item['url'],
                title=item['title'],
                category=item['category'],
                conent=item['content'],
                author_name=item['author_name']
            )
            list_dict.append(obj)
        Headlines.objects.bulk_create(list_dict)
    cur_date = datetime.datetime.now().date()
    # 前四天
    day = cur_date - datetime.timedelta(days=7)
    # 查询前一周数据，也可以用range
    Headlines.objects.filter(add_time__lte=day).delete()
    return HttpResponse({'ee': '43'})


from apps.article.tasks import add, error_email, conf


def addModel(request):
    add.delay()
    print('定时任务')
    return HttpResponse('ok')


@login_required(login_url='/login')
def ArticleMe(request):
    '''
    我关注的人的文章
    :param request:
    :return:
    '''
    article = Article.objects.filter(authors__follow__fan_id=request.user.id, is_show=True)
    category = Category_Article.objects.all()
    type = request.GET.get('type', '')
    try:
        page = request.GET.get('page', 1)
        if type:
            article = Article.objects.filter(authors__follow__fan_id=request.user.id, category_id=type, is_show=True)
        if page == '':
            page = 1
    except PageNotAnInteger:
        page = 1
    p = Paginator(article, 10, request=request)
    people = p.page(page)
    headlines = Headlines.objects.all()[:20]
    banners = Banners.objects.first()
    return render(request, 'pc/article_me.html',
                  {'article': people, 'category': category, 'Headlines': headlines, 'banners': banners})


@login_required(login_url='/login')
def Article_Add(request):
    '''
    新增文章
    :param request:
    :return:
    '''
    if request.method == 'GET':
        category = Category_Article.objects.all()
        return render(request, 'pc/articlesadd.html', {"category": category})

    if request.method == 'POST':
        forms = Article_form(request.POST)
        if forms.is_valid():
            title = forms.cleaned_data.get('title')
            content = forms.cleaned_data.get('content')
            category = request.POST.get('category', '')
            desc = request.POST.get('desc', '')
            keywords = request.POST.get('keywords', '')
            list_pic = request.FILES.get('list_pic', '')
            authors = forms.cleaned_data.get('authors', '')
            article = Article()
            article.title = title
            article.content = content
            article.desc = desc
            article.keywords = keywords
            article.authors = authors
            article.category_id = int(category)
            article.list_pic = list_pic
            try:
                article.save()
                return JsonResponse({"code": 200, "data": "发布成功"})
            except Exception:
                return JsonResponse({"code": 400, "data": "发布失败"})
        return JsonResponse({"code": 400, "data": "验证失败"})


@login_required(login_url='/login')
def ArticleUpdate(request, article_id):
    """
    文章修改
    :param request:
    :param article_id:
    :return:
    """
    if request.method == 'GET':
        category = Category_Article.objects.all()
        try:
            article = Article.objects.get(id=article_id)
        except Exception:
            return Http404
        return render(request, 'pc/article_update.html', {'article': article, 'category': category})
    if request.method == 'POST':
        forms = Article_form(request.POST)
        if forms.is_valid():
            title = forms.cleaned_data.get('title')
            content = forms.cleaned_data.get('content')
            category = request.POST.get('category', '')
            desc = request.POST.get('desc', '')
            keywords = request.POST.get('keywords', '')
            type = request.POST.get('type', '')
            if type:
                list_pic = request.FILES.get('list_pic', '')
            else:
                list_pic = request.POST.get('list_pic', '')
            authors = forms.cleaned_data.get('authors', '')
            article = Article.objects.get(id=article_id)
            article.title = title
            article.content = content
            article.desc = desc
            article.keywords = keywords
            article.authors = authors
            article.category_id = int(category)
            article.list_pic = list_pic
            try:
                article.save()
                return JsonResponse({"code": 200, "data": "发布成功"})
            except Exception:
                return JsonResponse({"code": 400, "data": "发布失败"})

templates/pc/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
    <!-- 页面关键词 keywords -->
    <meta name="keywords" content="{% block keywords %}
    {% endblock %}">
    <!-- 页面描述内容 description -->
    <meta name="description" content="{% block desc %}
    {% endblock %}">
    <!-- 定义网页作者 author -->
    <meta name="author" content="{% block authors %}

    {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/public.css' %}">
    {% block css %}{% endblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.min.js' %}"></script>
    <script src="{% static 'js/public.js' %}"></script>
    <script src="{% static 'js/xss.js' %}"></script>
    {% block link_js %}
    {% endblock %}
</head>
<body>
<header>
    <div class="main clearfix">
        <div class="fl logo"style="height: 60px"><img style="width: 40px;margin-top: 20px;" src="{% static 'img/logo.png' %}" alt=""></div>
        <nav class="fl">
            <ul class="clearfix headers_nav">
                <li class="fl"><a class="{% if request.path == '/' %}
                active
                {% endif %}" href="{% url 'home' %}">首页</a></li>
                <li class="fl"><a class=" {% if request.path|slice:'9' == '/article/' %}
                active
                {% endif %}"href="{% url 'article:index' %}">文章</a></li>

                <li class="fl"><a class=" {% if request.path|slice:'8' == '/course/' %}
                active
                {% endif %} "href="{% url 'course:index' %}">教程</a></li>
             <li class="fl"><a class=" {% if request.path|slice:'7' == '/forum/' %}
                active
                {% endif %}" href="{% url 'forum:forum' %}">社区论坛</a></li>
                <li class="fl"><a class=" {% if request.path|slice:'9' == '/support/' %}
                active
                {% endif %}" href="{% url 'support:support' %}">支持与赞助</a></li>
            </ul>
        </nav>
        <div class="fr user">
            <ul class="clearfix"style="display:flex;display: -webkit-flex;">
            <li>
                <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                  <input type="text" name="q" placeholder="搜索" required class="form_control">
{#                  <button type="submit">#}
                      <button type="submit" class="form_search"></button>
{#                  </button>#}
                </form>
            </li>
                <li class="fl style" style="background: url({% static 'img/public.png' %})no-repeat 0 50%;"><a href="{% url 'article:created' %}">写文章</a></li>
                <li class="fl style" style="background: url({% static 'img/phone.png' %})no-repeat 0 50%;"><a href="">手机阅读</a></li>
                {% if request.user.is_authenticated %}
                    <li class="fl avatar">
                        <a class="img_cover" style="background: url({% if request.user.user_imag %}
                            {{ MEDIA_URL }}{{ request.user.user_imag  }}
                            {% elif request.user.user_image %}
                            {{ request.user.user_image }}
                            {% else %}
                            {% static 'img/pc-icon.png' %}
                        {% endif %})no-repeat;">
                        <b id="yuan" style="width: 10px;height: 10px;
                        position: absolute;
                        display: none;
                        right: 0;
                        background: red;-webkit-border-radius: 50%;-moz-border-radius: 50%;border-radius: 50%;"></b>
                        </a>
                        <ul class="meau meau_hide">
                            <li><a href="{% url 'user:person' %}">个人中心</a></li>
                         <li><a href="{% url 'user:message' %}">消息<span class="badge"></span></a></li>
                            {% if user.is_staff  %}
                                <li><a href="">系统管理</a></li>
                            {% endif %}
                            <li><a href="{% url 'logou' %}">退出</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="fl"><a href="/login">登录 </a> | <a href="{% url 'register' %}"> 注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>
{% block content %}

{% endblock %}

<footer class="footer">
    <p class="main">Powered by
        <a>会飞的小席</a>
                    <a href="http://www.miitbeian.gov.cn" target="_blank">沪ICP备19083244号-1</a>


    </p>

</footer>
 <a href="javascript:;" id="toTop"></a>
<script>
    $(function(){
        {% if request.user.is_authenticated %}

        $.ajax({
            url:'/info/',
            type:'get',
            success:function (data) {
                $('span.badge').text(data.count)
                if(data.count>0){
                    $("#yuan").show()
                }
            }
        })
        {% endif %}

        $('.avatar').click(function(event){
            event.stopPropagation();
            $('.meau').fadeIn()
        })
        $(document).click(function(){
            $(".meau").fadeOut();
            });
        $(window).scroll(function(){
                if ($(window).scrollTop()>100){
                    $("#toTop").fadeIn(1500);
                }
                else
                {
                    $("#toTop").fadeOut(1000);
                }
        });
            //当点击跳转链接后，回到页面顶部位置
            $("#toTop").click(function(){
                $('body,html').animate({scrollTop:0},500);
                return false;
            });
        //底部栏位置始终在最底部
        //console.log(window.screen.availHeight)
        $("body").css({
            "min-height": $(window).height()
        })
    })
</script>
{% block js %}
{% endblock %}
</body>
</html>

templates/pc/forum.html
{% extends 'pc/base.html' %}
{% load static %}
{% block title %}
社区论坛
{% endblock %}
{% block authors %}
author 冯金琪
{% endblock %}
{% block keywords %}
问题求助、代码、技术分享、综合讨论、求职招聘
{% endblock %}
{% block desc %}
问题求助、代码、技术分享、综合讨论，在这里你可以进行技术分享、帮助别人解决问题。求职招聘，网站反馈等
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/forum.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

{% endblock %}
{% block js %}
    <script src="{% static 'js/public.js' %}"></script>
{% endblock %}
{% block content %}
    <section class="main" style="overflow: hidden">
        <article class="fl">
        <div class="forum">
            {% if plate %}
              <ul id="plate" class="clearfix">
                {% for foo in plate %}
                    <li class="flex">
                        <div class="tieImg"><img src="{{ MEDIA_URL }}{{ foo.image }}" alt=""></div>
                        <div>
                            <div class="tieNUm">{{ foo.get_count}}</div>
                            <div class="tieNmae"><a href="{% url 'forum:id' foo.id%}">{{ foo.name }}</a></div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            {% endif %}

        {% block childer %}
         <div style="background: #fff;">
            <div class="f-name">
                <span class="active">最新帖子</span>
            </div>

            <ul class="list">
                {% for foo in people.object_list %}
                    <li class="clearfix">
                        <img src="{% if foo.authors.user_imag %}
                    {{ MEDIA_URL }}{{ foo.authors.user_imag }}
                    {% elif foo.authors.user_image %}
                        {{ foo.authors.user_image }}
                        {% else %}
                        {% static 'img/pc-icon.png' %}
                    {% endif %}" class="user fl" title="{{ foo.authors.username }}"width="40px">
                    <div class="list-text fl">
                        <div class="fl">
                                 <p class="forun-title"><a href="{% url 'forum:detail' foo.id %}">{{ foo.title |truncatechars:130}}</a></p>
                        <p class="forun-info">来自于 {{ foo.category.name }}  {{ foo.add_time }} </p>
                        </div>

                           <div class="fr flex forun-num">
                        <div>评论{{ foo.get_number }}</div>
                        <div>浏览 {{ foo.click_nums}}</div>
                    </div>
                    </div>

                    </li>
                {% endfor %}
            </ul>


                 {% if people.object_list.count >= 1 %}
        <div class="pageturn"style="padding: 15px">
           <ul class="pagination">
{#               <li><a href="/index">首页</a></li>#}
               {% if people.has_previous %}
                   <li class="long"><a href="?{{ people.previous_page_number.querystring }}" class="prev">上一页</a></li>
               {% else %}
                   <li class="long"><span class="disabled prev btn"disabled="">上一页</span></li>
               {% endif %}
               {% for page in people.pages %}
                   {% if page %}
                       {% ifequal page people.number %}
                           <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                       {% else %}
                           <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                       {% endifequal %}
                   {% else %}
                       <li><span class="disabled  btn" disabled="">...</span></li>
                   {% endif %}
               {% endfor %}
               {% if people.has_next %}
                   <li class="long"><a href="?{{ people.next_page_number.querystring }}" class="next"> 下一页</a></li>
               {% else %}
                   <li class="long"><span class="disabled next btn"disabled=""> 下一页</span></li>
               {% endif %}
{#               <li><a href="?page={{ article.paginator.num_pages }}">尾页</a></li>#}
               <li class="hrefto">跳转到<input type="text"class="form-control" name="page"></li>
           </ul>

            当前{{ people.number }}/总共{{ people.paginator.num_pages }}页
       </div>
    {% endif %}








        </div>


        {% endblock %}

        </div>
        </article>
         <aside class="fr">
             <div class="sidebar">
                <p class="fa">
                    <a class="meun_fa" href="{% url 'forum:add' %}">发布新帖子</a>
                </p>
             </div>
             {% load forum %}
             {% get_fourm %}
         </aside>
    </section>
{% endblock %}

templates/pc/message.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
</head>
<body>
<p>{{ message|safe }}</p>
</body>
</html>